import React, { useState, useCallback } from 'react';
import './App.css';
import axios from 'axios';
import { Button } from './components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select';
import { Textarea } from './components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './components/ui/tabs';
import { Badge } from './components/ui/badge';
import { Alert, AlertDescription } from './components/ui/alert';
import { Input } from './components/ui/input';
import { Switch } from './components/ui/switch';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from './components/ui/collapsible';
import { Download, Upload, FileText, Database, ArrowRight, Code2, RefreshCw, Settings, ChevronDown } from 'lucide-react';
import { useToast } from './hooks/use-toast';
import { Toaster } from './components/ui/toaster';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

function App() {
  const [sourceDatabase, setSourceDatabase] = useState('');
  const [sqlInput, setSqlInput] = useState('');
  const [convertedSql, setConvertedSql] = useState('');
  const [warnings, setWarnings] = useState([]);
  const [isConverting, setIsConverting] = useState(false);
  const [conversionId, setConversionId] = useState('');
  const [activeTab, setActiveTab] = useState('text');
  const [selectedFile, setSelectedFile] = useState(null);
  
  // New state for enhanced instructions
  const [sourceDatabaseName, setSourceDatabaseName] = useState('');
  const [sourceSchemaName, setSourceSchemaName] = useState('');
  const [targetDatabaseName, setTargetDatabaseName] = useState('');
  const [targetSchemaName, setTargetSchemaName] = useState('');
  const [customInstructions, setCustomInstructions] = useState('');
  const [includeComments, setIncludeComments] = useState(true);
  const [preserveCase, setPreserveCase] = useState(false);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  
  const { toast } = useToast();

  // Sample SQL for different databases
  const sampleSql = {
    mysql: `CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
    postgresql: `CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);`,
    sqlserver: `CREATE TABLE users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    email NVARCHAR(100) UNIQUE,
    created_at DATETIME2 DEFAULT GETDATE(),
    is_active BIT DEFAULT 1
);`,
    oracle: `CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    created_at TIMESTAMP DEFAULT SYSDATE,
    is_active NUMBER(1) DEFAULT 1
);`
  };

  const loadSampleSql = () => {
    if (sourceDatabase && sampleSql[sourceDatabase]) {
      setSqlInput(sampleSql[sourceDatabase]);
    }
  };

  const handleConvert = async () => {
    if (!sqlInput.trim() || !sourceDatabase) {
      toast({
        title: "Validation Error",
        description: "Please provide SQL content and select source database",
        variant: "destructive"
      });
      return;
    }

    setIsConverting(true);
    try {
      const response = await axios.post(`${API}/convert`, {
        sql_content: sqlInput,
        source_database: sourceDatabase,
        conversion_type: 'basic',
        source_database_name: sourceDatabaseName || null,
        source_schema_name: sourceSchemaName || null,
        target_database_name: targetDatabaseName || null,
        target_schema_name: targetSchemaName || null,
        custom_instructions: customInstructions || null,
        include_comments: includeComments,
        preserve_case: preserveCase
      });

      setConvertedSql(response.data.converted_sql);
      setWarnings(response.data.warnings || []);
      setConversionId(response.data.id);
      
      toast({
        title: "Conversion Successful",
        description: `SQL converted from ${sourceDatabase.toUpperCase()} to Snowflake`,
      });
    } catch (error) {
      console.error('Conversion error:', error);
      toast({
        title: "Conversion Failed",
        description: error.response?.data?.detail || "Failed to convert SQL",
        variant: "destructive"
      });
    } finally {
      setIsConverting(false);
    }
  };

  const handleFileUpload = useCallback(async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    if (!sourceDatabase) {
      toast({
        title: "Select Database",
        description: "Please select source database before uploading file",
        variant: "destructive"
      });
      return;
    }

    setSelectedFile(file);
    setIsConverting(true);

    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('source_database', sourceDatabase);
      if (sourceDatabaseName) formData.append('source_database_name', sourceDatabaseName);
      if (sourceSchemaName) formData.append('source_schema_name', sourceSchemaName);
      if (targetDatabaseName) formData.append('target_database_name', targetDatabaseName);
      if (targetSchemaName) formData.append('target_schema_name', targetSchemaName);
      if (customInstructions) formData.append('custom_instructions', customInstructions);
      formData.append('include_comments', includeComments);
      formData.append('preserve_case', preserveCase);

      const response = await axios.post(`${API}/convert-file`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      setSqlInput(response.data.original_sql);
      setConvertedSql(response.data.converted_sql);
      setWarnings(response.data.warnings || []);
      setConversionId(response.data.id);
      
      toast({
        title: "File Converted Successfully",
        description: `${file.name} converted from ${sourceDatabase.toUpperCase()} to Snowflake`,
      });
    } catch (error) {
      console.error('File conversion error:', error);
      toast({
        title: "File Conversion Failed",
        description: error.response?.data?.detail || "Failed to convert file",
        variant: "destructive"
      });
    } finally {
      setIsConverting(false);
    }
  }, [sourceDatabase, sourceDatabaseName, sourceSchemaName, targetDatabaseName, targetSchemaName, customInstructions, includeComments, preserveCase, toast]);

  const handleDownload = async () => {
    if (!conversionId) {
      toast({
        title: "No Conversion",
        description: "Please convert SQL first before downloading",
        variant: "destructive"
      });
      return;
    }

    try {
      const response = await axios.get(`${API}/download/${conversionId}`, {
        responseType: 'blob'
      });

      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `snowflake_converted_${conversionId.substring(0, 8)}.sql`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);

      toast({
        title: "Download Started",
        description: "Converted SQL file is being downloaded",
      });
    } catch (error) {
      console.error('Download error:', error);
      toast({
        title: "Download Failed",
        description: "Failed to download converted SQL",
        variant: "destructive"
      });
    }
  };

  const clearAll = () => {
    setSqlInput('');
    setConvertedSql('');
    setWarnings([]);
    setConversionId('');
    setSelectedFile(null);
    setTargetDatabaseName('');
    setTargetSchemaName('');
    setCustomInstructions('');
    setIncludeComments(true);
    setPreserveCase(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Database className="h-8 w-8 text-blue-600" />
            <ArrowRight className="h-6 w-6 text-gray-400" />
            <div className="bg-blue-600 text-white px-3 py-1 rounded-lg font-semibold">Snowflake</div>
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">SQL to Snowflake Converter</h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Transform your SQL from MySQL, PostgreSQL, SQL Server, and Oracle to Snowflake-compatible syntax
          </p>
        </div>

        {/* Main Conversion Interface */}
        <div className="max-w-7xl mx-auto">
          {/* Controls */}
          <Card className="mb-6">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Code2 className="h-5 w-5" />
                Conversion Settings
              </CardTitle>
              <CardDescription>
                Select your source database and input method
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col lg:flex-row gap-4 items-start lg:items-end">
                <div className="flex-1">
                  <label className="text-sm font-medium mb-2 block">Source Database</label>
                  <Select value={sourceDatabase} onValueChange={setSourceDatabase}>
                    <SelectTrigger data-testid="source-database-select">
                      <SelectValue placeholder="Select source database" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="mysql">MySQL</SelectItem>
                      <SelectItem value="postgresql">PostgreSQL</SelectItem>
                      <SelectItem value="sqlserver">SQL Server</SelectItem>
                      <SelectItem value="oracle">Oracle</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    onClick={loadSampleSql}
                    disabled={!sourceDatabase}
                    data-testid="load-sample-btn"
                  >
                    <FileText className="h-4 w-4 mr-2" />
                    Load Sample
                  </Button>
                  <Button 
                    variant="outline" 
                    onClick={clearAll}
                    data-testid="clear-all-btn"
                  >
                    <RefreshCw className="h-4 w-4 mr-2" />
                    Clear All
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Advanced Instructions Section */}
          <Card className="mb-6">
            <Collapsible open={showAdvancedOptions} onOpenChange={setShowAdvancedOptions}>
              <CollapsibleTrigger asChild>
                <CardHeader className="cursor-pointer hover:bg-gray-50 transition-colors">
                  <CardTitle className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Settings className="h-5 w-5" />
                      Advanced Options & Instructions
                    </div>
                    <ChevronDown className={`h-4 w-4 transition-transform ${showAdvancedOptions ? 'rotate-180' : ''}`} />
                  </CardTitle>
                  <CardDescription>
                    Configure target database settings and provide custom conversion instructions
                  </CardDescription>
                </CardHeader>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <CardContent className="pt-0">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                    <div>
                      <label className="text-sm font-medium mb-2 block">Target Database Name</label>
                      <Input
                        placeholder="e.g., PROD_DB, ANALYTICS_DB"
                        value={targetDatabaseName}
                        onChange={(e) => setTargetDatabaseName(e.target.value)}
                        data-testid="target-database-input"
                      />
                      <p className="text-xs text-gray-500 mt-1">Will add USE DATABASE statement</p>
                    </div>
                    <div>
                      <label className="text-sm font-medium mb-2 block">Target Schema Name</label>
                      <Input
                        placeholder="e.g., PUBLIC, STAGING, PROD"
                        value={targetSchemaName}
                        onChange={(e) => setTargetSchemaName(e.target.value)}
                        data-testid="target-schema-input"
                      />
                      <p className="text-xs text-gray-500 mt-1">Will qualify table names with schema</p>
                    </div>
                  </div>
                  
                  <div className="mb-4">
                    <label className="text-sm font-medium mb-2 block">Custom Instructions</label>
                    <Textarea
                      placeholder="e.g., Use warehouse COMPUTE_WH, Add clustering on date columns, Apply partitioning by year..."
                      value={customInstructions}
                      onChange={(e) => setCustomInstructions(e.target.value)}
                      className="min-h-[80px]"
                      data-testid="custom-instructions-textarea"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Provide specific requirements like warehouse settings, clustering, partitioning, etc.
                    </p>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="flex items-center justify-between p-3 border rounded-lg">
                      <div>
                        <label className="text-sm font-medium">Include Comments</label>
                        <p className="text-xs text-gray-500">Preserve original comments in converted SQL</p>
                      </div>
                      <Switch
                        checked={includeComments}
                        onCheckedChange={setIncludeComments}
                        data-testid="include-comments-switch"
                      />
                    </div>
                    <div className="flex items-center justify-between p-3 border rounded-lg">
                      <div>
                        <label className="text-sm font-medium">Preserve Case</label>
                        <p className="text-xs text-gray-500">Keep original object name casing</p>
                      </div>
                      <Switch
                        checked={preserveCase}
                        onCheckedChange={setPreserveCase}
                        data-testid="preserve-case-switch"
                      />
                    </div>
                  </div>
                </CardContent>
              </CollapsibleContent>
            </Collapsible>
          </Card>

          {/* Input Methods */}
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Input SQL</CardTitle>
              <CardDescription>
                Choose to paste SQL directly or upload a .sql file
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Tabs value={activeTab} onValueChange={setActiveTab}>
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="text" data-testid="text-input-tab">Text Input</TabsTrigger>
                  <TabsTrigger value="file" data-testid="file-upload-tab">File Upload</TabsTrigger>
                </TabsList>
                <TabsContent value="text" className="space-y-4">
                  <Textarea
                    data-testid="sql-input-textarea"
                    placeholder="Paste your SQL code here..."
                    value={sqlInput}
                    onChange={(e) => setSqlInput(e.target.value)}
                    className="min-h-[200px] font-mono text-sm"
                  />
                </TabsContent>
                <TabsContent value="file" className="space-y-4">
                  <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
                    <Upload className="h-12 w-12 mx-auto text-gray-400 mb-4" />
                    <div className="space-y-2">
                      <p className="text-sm text-gray-600">Upload your .sql file</p>
                      <input
                        type="file"
                        accept=".sql"
                        onChange={handleFileUpload}
                        className="hidden"
                        id="file-upload"
                        data-testid="file-upload-input"
                      />
                      <label htmlFor="file-upload">
                        <Button variant="outline" className="cursor-pointer" data-testid="upload-btn">
                          Choose File
                        </Button>
                      </label>
                      {selectedFile && (
                        <p className="text-sm text-green-600 mt-2">
                          Selected: {selectedFile.name}
                        </p>
                      )}
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
              
              <div className="flex justify-center pt-4">
                <Button 
                  onClick={handleConvert}
                  disabled={isConverting || !sqlInput.trim() || !sourceDatabase}
                  size="lg"
                  className="bg-blue-600 hover:bg-blue-700"
                  data-testid="convert-btn"
                >
                  {isConverting ? (
                    <>
                      <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                      Converting...
                    </>
                  ) : (
                    <>
                      <ArrowRight className="h-4 w-4 mr-2" />
                      Convert to Snowflake
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Results */}
          {convertedSql && (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-green-600">Conversion Complete</CardTitle>
                    <CardDescription>
                      Your SQL has been converted to Snowflake syntax
                    </CardDescription>
                  </div>
                  <Button onClick={handleDownload} data-testid="download-btn">
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {/* Applied Instructions Summary */}
                {(targetDatabaseName || targetSchemaName || customInstructions) && (
                  <Alert className="mb-6 bg-blue-50 border-blue-200" data-testid="applied-instructions-alert">
                    <Settings className="h-4 w-4" />
                    <AlertDescription>
                      <div className="space-y-2">
                        <p className="font-semibold">Applied Instructions:</p>
                        <ul className="space-y-1 text-sm">
                          {targetDatabaseName && (
                            <li>• Target Database: <code className="bg-blue-100 px-1 rounded">{targetDatabaseName}</code></li>
                          )}
                          {targetSchemaName && (
                            <li>• Target Schema: <code className="bg-blue-100 px-1 rounded">{targetSchemaName}</code></li>
                          )}
                          {customInstructions && (
                            <li>• Custom Instructions: <span className="italic">{customInstructions}</span></li>
                          )}
                          <li>• Comments: {includeComments ? 'Included' : 'Excluded'}</li>
                          <li>• Case: {preserveCase ? 'Preserved' : 'Standardized'}</li>
                        </ul>
                      </div>
                    </AlertDescription>
                  </Alert>
                )}

                {/* Warnings */}
                {warnings.length > 0 && (
                  <Alert className="mb-6" data-testid="warnings-alert">
                    <AlertDescription>
                      <div className="space-y-2">
                        <p className="font-semibold">Conversion Notes:</p>
                        <ul className="space-y-1">
                          {warnings.map((warning, index) => (
                            <li key={index} className="text-sm">
                              • {warning}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </AlertDescription>
                  </Alert>
                )}

                {/* Side-by-side comparison */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                        Original ({sourceDatabase?.toUpperCase()})
                      </Badge>
                    </div>
                    <div className="bg-gray-50 border rounded-lg p-4 max-h-96 overflow-auto">
                      <pre className="text-sm font-mono text-gray-800 whitespace-pre-wrap" data-testid="original-sql">
                        {sqlInput}
                      </pre>
                    </div>
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                        Converted (Snowflake)
                      </Badge>
                    </div>
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 max-h-96 overflow-auto">
                      <pre className="text-sm font-mono text-gray-800 whitespace-pre-wrap" data-testid="converted-sql">
                        {convertedSql}
                      </pre>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
      <Toaster />
    </div>
  );
}

export default App;